import Head from 'next/head'
import Image from 'next/image'

import NavBar from '../components/NavBar'
import Body from '../components/Body'

export default function Home() {
  return (
      <div>
        <Head>
          <title>Project Juen</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar></NavBar>
        <Body className="flex flex-col items-center">
          <h1 className="text-1xl m-10 md:text-5xl">
            Home page
          </h1>
        </Body>
      </div>
  )
}
